import { Logo } from "@/components/Logo"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Github Jobs",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`text-black bg-slate-100 ${poppins.className}`}>
        <main className="flex min-h-screen flex-col items-start p-6 w-full max-w-screen-xl m-auto">
          <Logo />
          {children}
        </main>
      </body>
    </html>
  )
}
